# Generated by Django 5.1.1 on 2026-06-03 05:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoliceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('force_number', models.CharField(help_text='Force Number', max_length=50, unique=True)),
                ('rank', models.CharField(choices=[('PC', 'PC'), ('CPL', 'CPL'), ('SGT', 'SGT'), ('S/SGT', 'S/SGT'), ('HCM', 'HCM'), ('AIP', 'AIP'), ('IP', 'IP'), ('ASP', 'ASP'), ('SP', 'SP'), ('SSP', 'SSP'), ('ACP', 'ACP'), ('CP', 'CP')], max_length=50)),
                ('station', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_expiry', models.DateTimeField(blank=True, null=True)),
                ('is_active_voter', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Election Admin'), ('VOTER', 'Voter')], default='VOTER', max_length=20)),
                ('must_change_password', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('VOTE', 'Vote Cast'), ('PASSWORD_CHANGE', 'Password Change'), ('ADMIN_CREATE', 'Admin Create (Legacy)'), ('ADMIN_UPDATE', 'Admin Update (Legacy)'), ('ADMIN_DELETE', 'Admin Delete (Legacy)'), ('ELECTION_CREATE', 'Election Created'), ('ELECTION_UPDATE', 'Election Updated'), ('ELECTION_DELETE', 'Election Deleted'), ('ELECTION_TOGGLE', 'Election Toggled'), ('CANDIDATE_CREATE', 'Candidate Created'), ('CANDIDATE_UPDATE', 'Candidate Updated'), ('CANDIDATE_DELETE', 'Candidate Deleted'), ('VOTER_CREATE', 'Voter Created'), ('VOTER_UPDATE', 'Voter Updated'), ('VOTER_DELETE', 'Voter Deleted'), ('VOTER_RESET_PASSWORD', 'Voter Password Reset'), ('VOTER_BULK_CREATE', 'Voters Bulk Created'), ('POSITION_CREATE', 'Position Created'), ('POSITION_UPDATE', 'Position Updated'), ('POSITION_DELETE', 'Position Deleted'), ('EXPORT_VOTERS', 'Voters Exported'), ('EXPORT_CANDIDATES', 'Candidates Exported'), ('EXPORT_RESULTS', 'Results Exported')], max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.TextField()),
                ('target_model', models.CharField(blank=True, max_length=50)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('eligible_ranks', models.CharField(blank=True, help_text='Comma-separated ranks', max_length=500)),
                ('eligible_stations', models.CharField(blank=True, help_text='Comma-separated stations', max_length=500)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='election_logos/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_elections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ElectionPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.election')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.position')),
            ],
            options={
                'unique_together': {('election', 'position')},
            },
        ),
        migrations.AddField(
            model_name='election',
            name='positions',
            field=models.ManyToManyField(related_name='elections', through='polls.ElectionPosition', to='polls.position'),
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('force_number', models.CharField(max_length=50)),
                ('rank', models.CharField(choices=[('PC', 'PC'), ('CPL', 'CPL'), ('SGT', 'SGT'), ('S/SGT', 'S/SGT'), ('HCM', 'HCM'), ('AIP', 'AIP'), ('IP', 'IP'), ('ASP', 'ASP'), ('SP', 'SP'), ('ACP', 'ACP'), ('CP', 'CP')], max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidates/')),
                ('biography', models.TextField(blank=True, help_text='Short manifesto')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='polls.election')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.position')),
            ],
            options={
                'ordering': ['position', 'name'],
                'unique_together': {('election', 'force_number')},
            },
        ),
        migrations.CreateModel(
            name='ElectionRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter_registrations', to='polls.election')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations_made', to=settings.AUTH_USER_MODEL)),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='election_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registered_at'],
                'unique_together': {('voter', 'election')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.election')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.position')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-voted_at'],
                'unique_together': {('voter', 'election', 'position')},
            },
        ),
    ]
