# Generated by Django 5.1.1 on 2026-04-08 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['position', 'name']},
        ),
        migrations.RemoveField(
            model_name='election',
            name='position',
        ),
        migrations.AddField(
            model_name='policeuser',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('VOTE', 'Vote Cast'), ('ADMIN_CREATE', 'Admin Create'), ('ADMIN_UPDATE', 'Admin Update'), ('PASSWORD_CHANGE', 'Password Change')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('election', 'force_number')},
        ),
        migrations.CreateModel(
            name='ElectionPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.election')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.position')),
            ],
            options={
                'unique_together': {('election', 'position')},
            },
        ),
        migrations.AddField(
            model_name='election',
            name='positions',
            field=models.ManyToManyField(related_name='elections', through='polls.ElectionPosition', to='polls.position'),
        ),
    ]
