# Generated by Django 5.1.1 on 2026-04-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_candidate_options_remove_election_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policeuser',
            name='rank',
            field=models.CharField(choices=[('CONSTABLE', 'Constable'), ('CORPORAL', 'Corporal'), ('SERGEANT', 'Sergeant'), ('INSPECTOR', 'Inspector'), ('ASP', 'Assistant Superintendent of Police')], max_length=50),
        ),
    ]
