# Generated by Django 5.1.1 on 2026-04-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_policeuser_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='target_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='target_model',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('VOTE', 'Vote Cast'), ('PASSWORD_CHANGE', 'Password Change'), ('ADMIN_CREATE', 'Admin Create (Legacy)'), ('ADMIN_UPDATE', 'Admin Update (Legacy)'), ('ADMIN_DELETE', 'Admin Delete (Legacy)'), ('ELECTION_CREATE', 'Election Created'), ('ELECTION_UPDATE', 'Election Updated'), ('ELECTION_DELETE', 'Election Deleted'), ('ELECTION_TOGGLE', 'Election Toggled'), ('CANDIDATE_CREATE', 'Candidate Created'), ('CANDIDATE_UPDATE', 'Candidate Updated'), ('CANDIDATE_DELETE', 'Candidate Deleted'), ('VOTER_CREATE', 'Voter Created'), ('VOTER_UPDATE', 'Voter Updated'), ('VOTER_DELETE', 'Voter Deleted'), ('VOTER_RESET_PASSWORD', 'Voter Password Reset'), ('VOTER_BULK_CREATE', 'Voters Bulk Created'), ('POSITION_CREATE', 'Position Created'), ('POSITION_UPDATE', 'Position Updated'), ('POSITION_DELETE', 'Position Deleted'), ('EXPORT_VOTERS', 'Voters Exported'), ('EXPORT_CANDIDATES', 'Candidates Exported'), ('EXPORT_RESULTS', 'Results Exported')], max_length=30),
        ),
        migrations.AlterField(
            model_name='policeuser',
            name='force_number',
            field=models.IntegerField(help_text='Force Number', unique=True),
        ),
    ]
