# Generated by Django 5.1.1 on 2026-04-25 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auditlog_target_id_auditlog_target_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='is_active',
        ),
    ]
