# Generated by Django 5.1.1 on 2026-04-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_electionregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='force_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='policeuser',
            name='force_number',
            field=models.CharField(help_text='Force Number', max_length=50, unique=True),
        ),
    ]
