# Generated by Django 5.1.1 on 2026-04-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_vote_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='election_logos/'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='rank',
            field=models.CharField(choices=[('CONSTABLE', 'Constable'), ('CORPORAL', 'Corporal'), ('SERGEANT', 'Sergeant'), ('INSPECTOR', 'Inspector'), ('ASP', 'Assistant Superintendent of Police')], max_length=50),
        ),
    ]
