# Generated by Django 5.1.1 on 2026-05-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_election_logo_alter_candidate_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='rank',
            field=models.CharField(choices=[('PC', 'Pc'), ('CPL', 'Cpl'), ('SGT', 'Sgt'), ('S/SGT', 'S/sgt'), ('HCM', 'Hcm'), ('AIP', 'Aip'), ('IP', 'Ip'), ('ASP', 'Asp'), ('SP', 'Sp'), ('ACP', 'Acp'), ('CP', 'Cp')], max_length=50),
        ),
        migrations.AlterField(
            model_name='policeuser',
            name='rank',
            field=models.CharField(choices=[('PC', 'Pc'), ('CPL', 'Cpl'), ('SGT', 'Sgt'), ('S/SGT', 'S/sgt'), ('HCM', 'Hcm'), ('AIP', 'Aip'), ('IP', 'Ip'), ('ASP', 'Asp'), ('SP', 'Sp'), ('ACP', 'Acp'), ('CP', 'Cp')], max_length=50),
        ),
    ]
