# Generated by Django 5.1.1 on 2026-05-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_alter_candidate_rank_alter_policeuser_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='rank',
            field=models.CharField(choices=[('PC', 'PC'), ('CPL', 'CPL'), ('SGT', 'SGT'), ('S/SGT', 'S/SGT'), ('HCM', 'HCM'), ('AIP', 'AIP'), ('IP', 'IP'), ('ASP', 'ASP'), ('SP', 'SP'), ('ACP', 'ACP'), ('CP', 'Cp')], max_length=50),
        ),
        migrations.AlterField(
            model_name='policeuser',
            name='rank',
            field=models.CharField(choices=[('PC', 'PC'), ('CPL', 'CPL'), ('SGT', 'SGT'), ('S/SGT', 'S/SGT'), ('HCM', 'HCM'), ('AIP', 'AIP'), ('IP', 'IP'), ('ASP', 'ASP'), ('SP', 'SP'), ('SSP', 'SSP'), ('ACP', 'ACP'), ('CP', 'CP')], max_length=50),
        ),
    ]
